/*
==================================================================
Object:			Table [dbo].[Settings]
Created:		08/03/2022
Last Update:	05/16/2025
Version:		v.9
Author:			Ivan Satmenic
Description:	This script sets the application setting defaults.
Note:			Update default values based on your environment.
==================================================================
*/

DECLARE 
-- Email Configuration
	@EmailConfigurationServer NVARCHAR(MAX),
	@EmailConfigurationPort NVARCHAR(MAX),
	@EmailConfigurationEnableSsl NVARCHAR(MAX),
	@EmailConfigurationUsername NVARCHAR(MAX),
	@EmailConfigurationPassword NVARCHAR(MAX),
	@EmailConfigurationSenderAddress NVARCHAR(MAX),
	@EmailConfigurationSenderName NVARCHAR(MAX),
	@EmailConfigurationEmailServiceType NVARCHAR(MAX),
-- Identity Configuration (Password Recepis, Account Lockout)
	@IdentityConfigurationLockoutAllowedForNewUsers NVARCHAR(MAX),
	@IdentityConfigurationLockoutDefaultLockoutTimeSpan NVARCHAR(MAX),
	@IdentityConfigurationLockoutMaxFailedAccessAttempts NVARCHAR(MAX),
	@IdentityConfigurationPasswordRequireDigit NVARCHAR(MAX),
	@IdentityConfigurationPasswordRequiredLength NVARCHAR(MAX),
	@IdentityConfigurationPasswordRequiredUniqueChars NVARCHAR(MAX),
	@IdentityConfigurationPasswordRequireLowercase NVARCHAR(MAX),
	@IdentityConfigurationPasswordRequireNonAlphanumeric NVARCHAR(MAX),
	@IdentityConfigurationPasswordRequireUppercase NVARCHAR(MAX),
	@IdentityConfigurationUserAllowedUserNameCharacters NVARCHAR(MAX),
	@IdentityConfigurationUserRequireUniqueEmail NVARCHAR(MAX),
-- IPS Identity Provider Configuration
	@IdpConfigurationAllowLocalLogin NVARCHAR(MAX),
	@IdpConfigurationAllowRegistration NVARCHAR(MAX),
	@IdpConfigurationAllowRememberLogin NVARCHAR(MAX),
	@IdpConfigurationAutomaticRedirectAfterSignOut NVARCHAR(MAX),
	@IdpConfigurationAutoProvisioningSG NVARCHAR(MAX),
	@IdpConfigurationAutoProvisioningProviders NVARCHAR(MAX),
	@IdpConfigurationCSPFrameAncestors NVARCHAR(MAX),
	@IdpConfigurationDisclaimer NVARCHAR(MAX),
	@IdpConfigurationDPCertThumbprint NVARCHAR(MAX),
	@IdpConfigurationDPUncShare NVARCHAR(MAX),
	@IdpConfigurationExpireTimeSpan NVARCHAR(MAX),
	@IdpConfigurationExternalLoginRoleClaimsPrefix NVARCHAR(MAX),
	@IdpConfigurationGoogleClientId NVARCHAR(MAX),
	@IdpConfigurationGoogleClientSecret NVARCHAR(MAX),
	@IdpConfigurationGoogleProxyServer NVARCHAR(MAX),
	@IdpConfigurationIncludeWindowsGroups NVARCHAR(MAX),
	@IdpConfigurationInvalidCredentialsErrorMessage NVARCHAR(MAX),
	@IdpConfigurationIssuerUri NVARCHAR(MAX),
	@IdpConfigurationKeyMgmtDeleteRetiredKeys NVARCHAR(MAX),
	@IdpConfigurationKeyMgmtPropagationTime NVARCHAR(MAX),
	@IdpConfigurationKeyMgmtRetentionDuration NVARCHAR(MAX),
	@IdpConfigurationKeyMgmtRotationInterval NVARCHAR(MAX),
	@IdpConfigurationOIDCAuthority NVARCHAR(MAX),
	@IdpConfigurationOIDCClientId NVARCHAR(MAX),
	@IdpConfigurationOIDCClientSecret NVARCHAR(MAX),
	@IdpConfigurationOIDCDisplayName NVARCHAR(MAX),
	@IdpConfigurationOIDCGetClaimsFromUserInfoEndpoint NVARCHAR(MAX),
	@IdpConfigurationOIDCProvider NVARCHAR(MAX),
	@IdpConfigurationOIDCResponseType NVARCHAR(MAX),
	@IdpConfigurationOIDCUsePkce NVARCHAR(MAX),
	@IdpConfigurationOIDCSaveTokens NVARCHAR(MAX),
	@IdpConfigurationOIDCScopes NVARCHAR(MAX),
	@IdpConfigurationOIDCProxyServer NVARCHAR(MAX),
	@IdpConfigurationProxyServer NVARCHAR(MAX),
	@IdpConfigurationProxyServerAddresses NVARCHAR(MAX),
	@IdpConfigurationProxyServerNetworks NVARCHAR(MAX),
	@IdpConfigurationProxyServerNumber NVARCHAR(MAX),
	@IdpConfigurationRaiseErrorEvents NVARCHAR(MAX),
	@IdpConfigurationRaiseFailureEvents NVARCHAR(MAX),
	@IdpConfigurationRaiseInformationEvents NVARCHAR(MAX),
	@IdpConfigurationRaiseSuccessEvents NVARCHAR(MAX),
	@IdpConfigurationRememberMeLoginDuration NVARCHAR(MAX),
	@IdpConfigurationShowLogoutPrompt NVARCHAR(MAX),
	@IdpConfigurationSlidingExpiration NVARCHAR(MAX),
	@IdpConfigurationURL NVARCHAR(MAX),
	@IdpConfigurationWindowsAuthenticationSchemeName NVARCHAR(MAX),
	@IdpConfigurationWsFederationDisplayButton NVARCHAR(MAX),
	@IdpConfigurationWsFederationMetadata NVARCHAR(MAX),
	@IdpConfigurationWsFederationWtrealm NVARCHAR(MAX),
	@IdpConfigurationWsFederationProxyServer NVARCHAR(MAX),
-- LDAP Quering Configuration
	@LdapConfigurationBindCredentials NVARCHAR(MAX),
	@LdapConfigurationBindDn NVARCHAR(MAX),
	@LdapConfigurationSearchBase NVARCHAR(MAX),
	@LdapConfigurationSSL NVARCHAR(MAX),
	@LdapConfigurationUrl NVARCHAR(MAX),
-- IPS Security Admin Configuration
	@sAdminConfigurationExpireTimeSpan NVARCHAR(MAX),
	@sAdminConfigurationRaiseErrorEvents NVARCHAR(MAX),
	@sAdminConfigurationRaiseFailureEvents NVARCHAR(MAX),
	@sAdminConfigurationRaiseInformationEvents NVARCHAR(MAX),
	@sAdminConfigurationRaiseSuccessEvents NVARCHAR(MAX),
	@sAdminConfigurationSlidingExpiration NVARCHAR(MAX)

SELECT
-- Email Configuration
	@EmailConfigurationServer = 'ipsenergy-com0i.mail.protection.outlook.com',
	@EmailConfigurationPort = '25',
	@EmailConfigurationEnableSsl = 'false',
	@EmailConfigurationUsername = NULL,
	@EmailConfigurationPassword = NULL,
	@EmailConfigurationSenderAddress = NULL,
	@EmailConfigurationSenderName = NULL,
	@EmailConfigurationEmailServiceType = 'SMTP',
-- Identity Configuration (Password Recepis, Account Lockout)
	@IdentityConfigurationLockoutAllowedForNewUsers = 'true',
	@IdentityConfigurationLockoutDefaultLockoutTimeSpan = '5',
	@IdentityConfigurationLockoutMaxFailedAccessAttempts = '5',
	@IdentityConfigurationPasswordRequireDigit = 'true',
	@IdentityConfigurationPasswordRequiredLength = '8',
	@IdentityConfigurationPasswordRequiredUniqueChars = '0',
	@IdentityConfigurationPasswordRequireLowercase = 'true',
	@IdentityConfigurationPasswordRequireNonAlphanumeric = 'true',
	@IdentityConfigurationPasswordRequireUppercase = 'true',
	@IdentityConfigurationUserAllowedUserNameCharacters = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._@+\',
	@IdentityConfigurationUserRequireUniqueEmail = 'false',
-- IPS Identity Provider Configuration
	@IdpConfigurationAllowLocalLogin = 'true',
	@IdpConfigurationAllowRegistration = 'false',
	@IdpConfigurationAllowRememberLogin = 'true',
	@IdpConfigurationAutomaticRedirectAfterSignOut = 'true',
	@IdpConfigurationAutoProvisioningSG = 'IPS_IdP_USERS',
	@IdpConfigurationAutoProvisioningProviders = 'Google OIDC WsFederation Windows',
	@IdpConfigurationCSPFrameAncestors = NULL,
	@IdpConfigurationDisclaimer = NULL,
	@IdpConfigurationDPCertThumbprint = NULL,
	@IdpConfigurationDPUncShare = NULL,
	@IdpConfigurationExpireTimeSpan = '24',
	@IdpConfigurationExternalLoginRoleClaimsPrefix = 'IPS_',
	@IdpConfigurationGoogleClientId = NULL,
	@IdpConfigurationGoogleClientSecret = NULL,
	@IdpConfigurationGoogleProxyServer = NULL,
	@IdpConfigurationIncludeWindowsGroups = 'true',
	@IdpConfigurationInvalidCredentialsErrorMessage = 'Oops, something went wrong!',
	@IdpConfigurationIssuerUri = NULL,
	@IdpConfigurationKeyMgmtDeleteRetiredKeys = 'false',
	@IdpConfigurationKeyMgmtPropagationTime = '2',
	@IdpConfigurationKeyMgmtRetentionDuration = '7',
	@IdpConfigurationKeyMgmtRotationInterval = '30',
	@IdpConfigurationOIDCAuthority = NULL,
	@IdpConfigurationOIDCClientId = NULL,
	@IdpConfigurationOIDCClientSecret = NULL,
	@IdpConfigurationOIDCDisplayName = NULL,
	@IdpConfigurationOIDCGetClaimsFromUserInfoEndpoint = NULL,
	@IdpConfigurationOIDCProvider = NULL,
	@IdpConfigurationOIDCResponseType = NULL,
	@IdpConfigurationOIDCUsePkce = NULL,
	@IdpConfigurationOIDCSaveTokens = NULL,
	@IdpConfigurationOIDCScopes = NULL,
	@IdpConfigurationOIDCProxyServer = NULL,
	@IdpConfigurationProxyServer = 'false',
	@IdpConfigurationProxyServerAddresses = NULL,
	@IdpConfigurationProxyServerNetworks = NULL,
	@IdpConfigurationProxyServerNumber = '1',
	@IdpConfigurationRaiseErrorEvents = 'true',
	@IdpConfigurationRaiseFailureEvents = 'true',
	@IdpConfigurationRaiseInformationEvents = 'true',
	@IdpConfigurationRaiseSuccessEvents = 'true',
	@IdpConfigurationRememberMeLoginDuration = '30',
	@IdpConfigurationShowLogoutPrompt = 'true',
	@IdpConfigurationSlidingExpiration = 'true',
	@IdpConfigurationURL = 'https://localhost:5443',
	@IdpConfigurationWindowsAuthenticationSchemeName = 'Windows',
	@IdpConfigurationWsFederationDisplayButton = NULL,
	@IdpConfigurationWsFederationMetadata = NULL,
	@IdpConfigurationWsFederationWtrealm = NULL,
	@IdpConfigurationWsFederationProxyServer = NULL,
-- LDAP Quering Configuration
	@LdapConfigurationBindCredentials = NULL,
	@LdapConfigurationBindDn = 'ldap01',
	@LdapConfigurationSearchBase = 'OU=IPS,DC=IPSHQ,DC=com',
	@LdapConfigurationSSL = 'true',
	@LdapConfigurationUrl = 'srvpdc01.ipshq.com',
-- IPS Security Admin Configuration
	@sAdminConfigurationExpireTimeSpan = '24',
	@sAdminConfigurationRaiseErrorEvents = 'true',
	@sAdminConfigurationRaiseFailureEvents = 'true',
	@sAdminConfigurationRaiseInformationEvents = 'true',
	@sAdminConfigurationRaiseSuccessEvents = 'true',
	@sAdminConfigurationSlidingExpiration = 'true'

BEGIN TRANSACTION;

WITH DefaultSettings AS (
	SELECT * FROM (VALUES
		-- Email Configuration
		('EmailConfiguration:Server', @EmailConfigurationServer),
		('EmailConfiguration:Port', @EmailConfigurationPort),
		('EmailConfiguration:EnableSsl', @EmailConfigurationEnableSsl),
		('EmailConfiguration:Username', @EmailConfigurationUsername),
		('EmailConfiguration:Password', @EmailConfigurationPassword),
		('EmailConfiguration:SenderAddress', @EmailConfigurationSenderAddress),
		('EmailConfiguration:SenderName', @EmailConfigurationSenderName),
		('EmailConfiguration:EmailServiceType', @EmailConfigurationEmailServiceType),
		-- Identity Configuration (Password Recepis, Account Lockout)
		('IdentityConfiguration:LockoutAllowedForNewUsers', @IdentityConfigurationLockoutAllowedForNewUsers),
		('IdentityConfiguration:LockoutDefaultLockoutTimeSpan', @IdentityConfigurationLockoutDefaultLockoutTimeSpan),
		('IdentityConfiguration:LockoutMaxFailedAccessAttempts', @IdentityConfigurationLockoutMaxFailedAccessAttempts),
		('IdentityConfiguration:PasswordRequireDigit', @IdentityConfigurationPasswordRequireDigit),
		('IdentityConfiguration:PasswordRequiredLength', @IdentityConfigurationPasswordRequiredLength),
		('IdentityConfiguration:PasswordRequiredUniqueChars', @IdentityConfigurationPasswordRequiredUniqueChars),
		('IdentityConfiguration:PasswordRequireLowercase', @IdentityConfigurationPasswordRequireLowercase),
		('IdentityConfiguration:PasswordRequireNonAlphanumeric', @IdentityConfigurationPasswordRequireNonAlphanumeric),
		('IdentityConfiguration:PasswordRequireUppercase', @IdentityConfigurationPasswordRequireUppercase),
		('IdentityConfiguration:UserAllowedUserNameCharacters', @IdentityConfigurationUserAllowedUserNameCharacters),
		('IdentityConfiguration:UserRequireUniqueEmail', @IdentityConfigurationUserRequireUniqueEmail),
		-- IPS Identity Provider Configuration
		('IdpConfiguration:AllowLocalLogin', @IdpConfigurationAllowLocalLogin),
		('IdpConfiguration:AllowRegistration', @IdpConfigurationAllowRegistration),
		('IdpConfiguration:AllowRememberLogin', @IdpConfigurationAllowRememberLogin),
		('IdpConfiguration:AutomaticRedirectAfterSignOut', @IdpConfigurationAutomaticRedirectAfterSignOut),
		('IdpConfiguration:AutoProvisioningSG', @IdpConfigurationAutoProvisioningSG),
		('IdpConfiguration:AutoProvisioningProviders', @IdpConfigurationAutoProvisioningProviders),
		('IdpConfiguration:CSPFrameAncestors', @IdpConfigurationCSPFrameAncestors),
		('IdpConfiguration:Disclaimer', @IdpConfigurationDisclaimer),
		('IdpConfiguration:DPCertThumbprint', @IdpConfigurationDPCertThumbprint),
		('IdpConfiguration:DPUncShare', @IdpConfigurationDPUncShare),
		('IdpConfiguration:ExpireTimeSpan', @IdpConfigurationExpireTimeSpan),
		('IdpConfiguration:ExternalLoginRoleClaimsPrefix', @IdpConfigurationExternalLoginRoleClaimsPrefix),
		('IdpConfiguration:GoogleClientId', @IdpConfigurationGoogleClientId),
		('IdpConfiguration:GoogleClientSecret', @IdpConfigurationGoogleClientSecret),
		('IdpConfiguration:GoogleProxyServer', @IdpConfigurationGoogleProxyServer),
		('IdpConfiguration:IncludeWindowsGroups', @IdpConfigurationIncludeWindowsGroups),
		('IdpConfiguration:InvalidCredentialsErrorMessage', @IdpConfigurationInvalidCredentialsErrorMessage),
		('IdpConfiguration:IssuerUri', @IdpConfigurationIssuerUri),
		('IdpConfiguration:KeyMgmtDeleteRetiredKeys', @IdpConfigurationKeyMgmtDeleteRetiredKeys),
		('IdpConfiguration:KeyMgmtPropagationTime', @IdpConfigurationKeyMgmtPropagationTime),
		('IdpConfiguration:KeyMgmtRetentionDuration', @IdpConfigurationKeyMgmtRetentionDuration),
		('IdpConfiguration:KeyMgmtRotationInterval', @IdpConfigurationKeyMgmtRotationInterval),
		('IdpConfiguration:OIDCAuthority', @IdpConfigurationOIDCAuthority),
		('IdpConfiguration:OIDCClientId', @IdpConfigurationOIDCClientId),
		('IdpConfiguration:OIDCClientSecret', @IdpConfigurationOIDCClientSecret),
		('IdpConfiguration:OIDCDisplayName', @IdpConfigurationOIDCDisplayName),
		('IdpConfiguration:OIDCGetClaimsFromUserInfoEndpoint', @IdpConfigurationOIDCGetClaimsFromUserInfoEndpoint),
		('IdpConfiguration:OIDCProvider', @IdpConfigurationOIDCProvider),
		('IdpConfiguration:OIDCResponseType', @IdpConfigurationOIDCResponseType),
		('IdpConfiguration:OIDCUsePkce', @IdpConfigurationOIDCUsePkce),
		('IdpConfiguration:OIDCSaveTokens', @IdpConfigurationOIDCSaveTokens),
		('IdpConfiguration:OIDCScopes', @IdpConfigurationOIDCScopes),
		('IdpConfiguration:OIDCProxyServer', @IdpConfigurationOIDCProxyServer),
		('IdpConfiguration:ProxyServer', @IdpConfigurationProxyServer),
		('IdpConfiguration:ProxyServerAddresses', @IdpConfigurationProxyServerAddresses),
		('IdpConfiguration:ProxyServerNetworks', @IdpConfigurationProxyServerNetworks),
		('IdpConfiguration:ProxyServerNumber', @IdpConfigurationProxyServerNumber),
		('IdpConfiguration:RaiseErrorEvents', @IdpConfigurationRaiseErrorEvents),
		('IdpConfiguration:RaiseFailureEvents', @IdpConfigurationRaiseFailureEvents),
		('IdpConfiguration:RaiseInformationEvents', @IdpConfigurationRaiseInformationEvents),
		('IdpConfiguration:RaiseSuccessEvents', @IdpConfigurationRaiseSuccessEvents),
		('IdpConfiguration:RememberMeLoginDuration', @IdpConfigurationRememberMeLoginDuration),
		('IdpConfiguration:ShowLogoutPrompt', @IdpConfigurationShowLogoutPrompt),
		('IdpConfiguration:SlidingExpiration', @IdpConfigurationSlidingExpiration),
		('IdpConfiguration:URL', @IdpConfigurationURL),
		('IdpConfiguration:WindowsAuthenticationSchemeName', @IdpConfigurationWindowsAuthenticationSchemeName),
		('IdpConfiguration:WsFederationDisplayButton', @IdpConfigurationWsFederationDisplayButton),
		('IdpConfiguration:WsFederationMetadata', @IdpConfigurationWsFederationMetadata),
		('IdpConfiguration:WsFederationWtrealm', @IdpConfigurationWsFederationWtrealm),
		('IdpConfiguration:WsFederationProxyServer', @IdpConfigurationWsFederationProxyServer),
		-- LDAP Quering Configuration
		('LdapConfiguration:BindCredentials', @LdapConfigurationBindCredentials),
		('LdapConfiguration:BindDn', @LdapConfigurationBindDn),
		('LdapConfiguration:SearchBase', @LdapConfigurationSearchBase),
		('LdapConfiguration:SSL', @LdapConfigurationSSL),
		('LdapConfiguration:Url', @LdapConfigurationUrl),
	-- IPS Security Admin Configuration
		('sAdminConfiguration:ExpireTimeSpan', @sAdminConfigurationExpireTimeSpan),
		('sAdminConfiguration:RaiseErrorEvents', @sAdminConfigurationRaiseErrorEvents),
		('sAdminConfiguration:RaiseFailureEvents', @sAdminConfigurationRaiseFailureEvents),
		('sAdminConfiguration:RaiseInformationEvents', @sAdminConfigurationRaiseInformationEvents),
		('sAdminConfiguration:RaiseSuccessEvents', @sAdminConfigurationRaiseSuccessEvents),
		('sAdminConfiguration:SlidingExpiration', @sAdminConfigurationSlidingExpiration)
) AS TempSettings ([Id], [Value]))

	MERGE INTO dbo.Settings AS Target
	USING DefaultSettings AS Source
	  ON Target.Id = Source.Id
	--WHEN MATCHED 
	--	THEN UPDATE 
	--		 SET Target.[Value] = Source.[Value]
	WHEN NOT MATCHED BY TARGET
		THEN INSERT ([Id], [Value])
			 VALUES (Source.[Id], Source.[Value])
	WHEN NOT MATCHED BY SOURCE
		THEN DELETE;

COMMIT;
